package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"text/tabwriter"

	"bindery/internal/bindery"
)

func JSON(w io.Writer, bs []bindery.Binding) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	return enc.Encode(bs)
}

func Table(w io.Writer, bs []bindery.Binding) {
	tw := tabwriter.NewWriter(w, 0, 2, 2, ' ', 0)
	fmt.Fprintln(tw, "SOURCE\tMODS\tKEY\tDESCRIPTION")
	for _, b := range bs {
		fmt.Fprintf(tw, "%s\t%s\t%s\t%s\n", b.Source, b.Mods, b.Key, b.Desc)
	}
	tw.Flush()
}

func Markdown(w io.Writer, bs []bindery.Binding) {
	fmt.Fprintln(w, "# Key Bindings (auto-generated)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Generated by`bindery --md`。Don't edit by hands.")
	fmt.Fprintln(w)
	cur := ""
	for _, b := range bs {
		if b.Source != cur {
			cur = b.Source
			fmt.Fprintf(w, "\n## %s\n\n", b.Source)
			fmt.Fprintln(w, "| Mods | Key | Description |")
			fmt.Fprintln(w, "|------|-----|------|")
		}
		fmt.Fprintf(w, "| %s | `%s` | %s |\n", mdEsc(b.Mods), b.Key, mdEsc(b.Desc))
	}
}

func mdEsc(s string) string { return strings.ReplaceAll(s, "|", "\\|") }
