package cli

import (
	"bytes"
	"slices"
	"strings"
	"testing"

	"bindery/internal/bindery"
)

func TestMdEsc(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
		skip bool
	}{
		{"空文字はそのまま空文字として扱う", "", "", false},
		{"|を含む文字列", "| a | b |", "\\| a \\| b \\|", false},
		{"|を含まない文字列", "abc", "abc", false},
		{"エスケープ済みの|はリテラルとして表示させる", "\\| a \\| b \\|", "\\\\\\| a \\\\\\| b \\\\\\|", true},
	}
	for _, tt := range cases {
		t.Run(tt.name, func(t *testing.T) {
			if tt.skip {
				t.Skip("issue#2:render.go:50を修正")
			}
			got := mdEsc(tt.in)
			if got != tt.want {
				t.Errorf("mdEsc(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

// markdownRows は Markdown の出力から見出し行とデータ行だけを順序を保って抜き出す。
// 固定ヘッダ・表ヘッダ・区切り行・空行は「ソースごとに見出し + 表」の検証には不要なので落とす。
func markdownRows(out string) []string {
	skip := map[string]bool{
		"":                                true,
		"# Key Bindings (auto-generated)": true,
		"Generated by`bindery --md`。Don't edit by hands.": true,
		"| Mods | Key | Description |":                    true,
		"|------|-----|------|":                           true,
	}
	var rows []string
	for line := range strings.SplitSeq(out, "\n") {
		if !skip[line] {
			rows = append(rows, line)
		}
	}
	return rows
}

func TestMarkdown(t *testing.T) {
	cases := []struct {
		name string
		in   []bindery.Binding
		want []string
	}{
		{
			name: "空なら表は出力されない",
			in:   nil,
			want: nil,
		},
		{
			name: "1ソースなら見出しは1つ",
			in: []bindery.Binding{
				{Source: "skhd", Mods: "cmd", Key: "a", Desc: "説明1"},
				{Source: "skhd", Mods: "cmd", Key: "b", Desc: "説明2"},
			},
			want: []string{
				"## skhd",
				"| cmd | `a` | 説明1 |",
				"| cmd | `b` | 説明2 |",
			},
		},
		{
			name: "2ソースなら見出しはソースごとに1つ",
			in: []bindery.Binding{
				{Source: "nvim", Mods: "", Key: "gd", Desc: "定義へ"},
				{Source: "skhd", Mods: "cmd", Key: "a", Desc: "説明1"},
			},
			want: []string{
				"## nvim",
				"|  | `gd` | 定義へ |",
				"## skhd",
				"| cmd | `a` | 説明1 |",
			},
		},
		{
			name: "ソート済みでない入力では同じソースの見出しが繰り返される",
			in: []bindery.Binding{
				{Source: "skhd", Mods: "cmd", Key: "a", Desc: "説明1"},
				{Source: "nvim", Mods: "", Key: "gd", Desc: "定義へ"},
				{Source: "skhd", Mods: "cmd", Key: "b", Desc: "説明2"},
			},
			want: []string{
				"## skhd",
				"| cmd | `a` | 説明1 |",
				"## nvim",
				"|  | `gd` | 定義へ |",
				"## skhd",
				"| cmd | `b` | 説明2 |",
			},
		},
	}
	for _, tt := range cases {
		t.Run(tt.name, func(t *testing.T) {
			var buf bytes.Buffer
			Markdown(&buf, tt.in)
			got := markdownRows(buf.String())
			if !slices.Equal(got, tt.want) {
				t.Errorf("Markdown() rows = %q, want %q", got, tt.want)
			}
		})
	}
}
